version: "3.5"

networks:
  nextcloud:
  nextcloud-internal:
volumes:
  nextcloud-html:
  nextcloud-apps:
  nextcloud-data:
  nextcloud-config:
  nextcloud-db:

services:
  ingress:
    networks:
      - nextcloud

  nextcloud:
    depends_on:
      - nextcloud-db
    deploy:
      labels:
        - traefik.frontend.rule=Host:cloud.${DOMAIN}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_nextcloud
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
      mode: global
      restart_policy:
        condition: any
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    image: nextcloud:16 # -fpm
    #<<: *logging-defaults
    networks:
      - nextcloud
      - nextcloud-internal
    volumes:
      - nextcloud-html:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config

  nextcloud-db:
    deploy:
      mode: global
      restart_policy:
        condition: any
    image: mariadb:10.4
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - nextcloud-internal
